version: 2

jobs:
  build:
    docker:
#      - image: circleci/openjdk:8-jdk
      - image: openjdk:7-jdk
#      - image: oracle/openjdk:7

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: apt-get update && apt-get install -y sudo

      - run:
          name: Install System Dependencies
          command: sudo apt-get update && sudo apt-get install -y maven

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn test

      # テスト結果の一覧(TEST-AppTest.xml)をTest Summaryに表示する
      - store_test_results:
          path: ~/repo/target/surefire-reports

      # Artifactsに表示するフォルダの設定(ファイルのアップロードなので時間がかかる)
#      - store_artifacts:
#          path: ~/
